name: widget_tester
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed: ^2.4.6
  dio: ^5.4.0
  go_router: ^13.1.0
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7


flutter:  
  uses-material-design: true
  assets:
    - assets/animations/
